//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2C2PService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallLog()
        {
            this.TransactionRecords = new HashSet<TransactionRecord>();
        }
    
        public int ID { get; set; }
        public string UserAgentName { get; set; }
        public string IPAddress { get; set; }
        public string FileType { get; set; }
        public int TransactionCount { get; set; }
        public bool IsSucceed { get; set; }
        public System.DateTime PushedOn { get; set; }
        public bool Active { get; set; }
        public int ServiceAccessRightID { get; set; }
    
        public virtual ServiceAccessRight ServiceAccessRight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRecord> TransactionRecords { get; set; }
    }
}
