//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2C2PService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRecord
    {
        public string TransactionID { get; set; }
        public int CallLogID { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Active { get; set; }
    
        public virtual CallLog CallLog { get; set; }
    }
}
